#!/usr/bin/env node
/**
 * Scaffolds a .env.local for first-time setup:
 * - Generates a strong PORTAL_SESSION_SECRET
 * - Leaves admin credentials and PORTAL_CLIENTS for the user to fill in
 *
 * Usage: npm run setup
 */
import { existsSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { resolve } from "node:path";

const target = resolve(process.cwd(), ".env.local");

if (existsSync(target)) {
  console.error(
    "\x1b[33m%s\x1b[0m",
    `.env.local already exists — refusing to overwrite.`,
  );
  console.error(`Edit it directly, or delete it and run 'npm run setup' again.`);
  process.exit(1);
}

const secret = randomBytes(32).toString("hex");

const body = `# Generated by scripts/setup.mjs on ${new Date().toISOString()}

# === Portal auth ===
PORTAL_SESSION_SECRET=${secret}

# Set these to the email + password Fox Valley Client Engine staff use to sign in.
PORTAL_ADMIN_EMAIL=owner@foxvalleyclientengine.com
PORTAL_ADMIN_PASSWORD=CHANGE_ME_TO_A_LONG_PASSWORD

# === HighLevel clients ===
# One entry per HighLevel sub-account. Create a Private Integration Token
# inside the sub-account (Settings -> Private Integrations -> Create new)
# with read scopes: contacts, opportunities, conversations, calendars, locations.
#
# Example — replace LOCATION_ID and pit-XXXX with your real values:
#
# PORTAL_CLIENTS=[{"id":"fvce","name":"Fox Valley Client Engine","locationId":"LOCATION_ID","pit":"pit-XXXX"}]
PORTAL_CLIENTS=[]
`;

writeFileSync(target, body);

console.log("\x1b[32m%s\x1b[0m", "Created .env.local with a fresh session secret.");
console.log("");
console.log("Next steps:");
console.log("  1. Open .env.local and set PORTAL_ADMIN_EMAIL + PORTAL_ADMIN_PASSWORD");
console.log("  2. Add at least one client to PORTAL_CLIENTS (see example in the file)");
console.log("  3. npm run dev");
